/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as proof from "./proof";
export type { proof };
export type { Getters } from "./Getters";
export type { Governance } from "./Governance";
export type { Setters } from "./Setters";
export type { Setup } from "./Setup";
export type { State } from "./State";
export type { ZKBridge } from "./ZKBridge";
export type { ZKBridgeEntrypoint } from "./ZKBridgeEntrypoint";
