/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ZKBridgeInterface extends utils.Interface {
  functions: {
    "MESSAGE_TOPIC()": FunctionFragment;
    "MIN_LOCK_TIME()": FunctionFragment;
    "blockUpdater(uint16)": FunctionFragment;
    "chainId()": FunctionFragment;
    "claimFees()": FunctionFragment;
    "confirmContractUpgrade()": FunctionFragment;
    "initialize()": FunctionFragment;
    "isInitialized(address)": FunctionFragment;
    "isL2()": FunctionFragment;
    "isTransferCompleted(bytes32)": FunctionFragment;
    "l2MessageReceive(uint16)": FunctionFragment;
    "l2MessageSend()": FunctionFragment;
    "lockTime()": FunctionFragment;
    "mptVerifier(uint16)": FunctionFragment;
    "nextSequence(bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "pendingImplementation()": FunctionFragment;
    "registerChain(uint16,bytes32)": FunctionFragment;
    "send(uint16,address,bytes)": FunctionFragment;
    "sendFromL2(uint16,uint16,address,bytes)": FunctionFragment;
    "setBlockUpdater(uint16,address)": FunctionFragment;
    "setL2(bool)": FunctionFragment;
    "setL2MessageReceive(uint16,address)": FunctionFragment;
    "setL2MessageSend(address)": FunctionFragment;
    "setLockTime(uint256)": FunctionFragment;
    "setMptVerifier(uint16,address)": FunctionFragment;
    "submitContractUpgrade(address)": FunctionFragment;
    "toUpdateTime()": FunctionFragment;
    "validateTransactionFromL2(uint16,address,address,uint64,bytes)": FunctionFragment;
    "validateTransactionProof(uint16,bytes32,uint256,bytes)": FunctionFragment;
    "zkBridgeContracts(uint16)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MESSAGE_TOPIC"
      | "MIN_LOCK_TIME"
      | "blockUpdater"
      | "chainId"
      | "claimFees"
      | "confirmContractUpgrade"
      | "initialize"
      | "isInitialized"
      | "isL2"
      | "isTransferCompleted"
      | "l2MessageReceive"
      | "l2MessageSend"
      | "lockTime"
      | "mptVerifier"
      | "nextSequence"
      | "owner"
      | "pendingImplementation"
      | "registerChain"
      | "send"
      | "sendFromL2"
      | "setBlockUpdater"
      | "setL2"
      | "setL2MessageReceive"
      | "setL2MessageSend"
      | "setLockTime"
      | "setMptVerifier"
      | "submitContractUpgrade"
      | "toUpdateTime"
      | "validateTransactionFromL2"
      | "validateTransactionProof"
      | "zkBridgeContracts"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MESSAGE_TOPIC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LOCK_TIME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blockUpdater",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "chainId", values?: undefined): string;
  encodeFunctionData(functionFragment: "claimFees", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "confirmContractUpgrade",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "isL2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isTransferCompleted",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "l2MessageReceive",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "l2MessageSend",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lockTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mptVerifier",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "nextSequence",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerChain",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sendFromL2",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setBlockUpdater",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setL2",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setL2MessageReceive",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setL2MessageSend",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLockTime",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMptVerifier",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "submitContractUpgrade",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "toUpdateTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateTransactionFromL2",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateTransactionProof",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "zkBridgeContracts",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "MESSAGE_TOPIC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LOCK_TIME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockUpdater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chainId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmContractUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isL2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTransferCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2MessageReceive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2MessageSend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mptVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextSequence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sendFromL2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBlockUpdater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setL2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setL2MessageReceive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setL2MessageSend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMptVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitContractUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toUpdateTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTransactionFromL2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTransactionProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zkBridgeContracts",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "ContractUpgraded(address,address)": EventFragment;
    "ExecutedMessage(address,uint16,uint64,address,bytes)": EventFragment;
    "MessagePublished(address,uint16,uint64,address,bytes)": EventFragment;
    "NewPendingImplementation(address,address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContractUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutedMessage"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MessagePublished"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewPendingImplementation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface ContractUpgradedEventObject {
  oldContract: string;
  newContract: string;
}
export type ContractUpgradedEvent = TypedEvent<
  [string, string],
  ContractUpgradedEventObject
>;

export type ContractUpgradedEventFilter =
  TypedEventFilter<ContractUpgradedEvent>;

export interface ExecutedMessageEventObject {
  sender: string;
  srcChainId: number;
  sequence: BigNumber;
  dstAddress: string;
  payload: string;
}
export type ExecutedMessageEvent = TypedEvent<
  [string, number, BigNumber, string, string],
  ExecutedMessageEventObject
>;

export type ExecutedMessageEventFilter = TypedEventFilter<ExecutedMessageEvent>;

export interface MessagePublishedEventObject {
  sender: string;
  dstChainId: number;
  sequence: BigNumber;
  dstAddress: string;
  payload: string;
}
export type MessagePublishedEvent = TypedEvent<
  [string, number, BigNumber, string, string],
  MessagePublishedEventObject
>;

export type MessagePublishedEventFilter =
  TypedEventFilter<MessagePublishedEvent>;

export interface NewPendingImplementationEventObject {
  pendingImplementation: string;
  newImplementation: string;
}
export type NewPendingImplementationEvent = TypedEvent<
  [string, string],
  NewPendingImplementationEventObject
>;

export type NewPendingImplementationEventFilter =
  TypedEventFilter<NewPendingImplementationEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface ZKBridge extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ZKBridgeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MESSAGE_TOPIC(overrides?: CallOverrides): Promise<[string]>;

    MIN_LOCK_TIME(overrides?: CallOverrides): Promise<[BigNumber]>;

    blockUpdater(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    chainId(overrides?: CallOverrides): Promise<[number]>;

    claimFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    confirmContractUpgrade(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isInitialized(
      impl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isL2(overrides?: CallOverrides): Promise<[boolean]>;

    isTransferCompleted(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    l2MessageReceive(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    l2MessageSend(overrides?: CallOverrides): Promise<[string]>;

    lockTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    mptVerifier(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    nextSequence(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pendingImplementation(overrides?: CallOverrides): Promise<[string]>;

    registerChain(
      chainId: PromiseOrValue<BigNumberish>,
      bridgeContract: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    send(
      dstChainId: PromiseOrValue<BigNumberish>,
      dstAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendFromL2(
      srcChainId: PromiseOrValue<BigNumberish>,
      dstChainId: PromiseOrValue<BigNumberish>,
      dstAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBlockUpdater(
      chainId: PromiseOrValue<BigNumberish>,
      blockUpdater: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setL2(
      isL2: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setL2MessageReceive(
      chainId: PromiseOrValue<BigNumberish>,
      l2MessageReceive: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setL2MessageSend(
      l2MessageSend: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLockTime(
      lockTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMptVerifier(
      chainId: PromiseOrValue<BigNumberish>,
      mptVerifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitContractUpgrade(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    toUpdateTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    validateTransactionFromL2(
      srcChainId: PromiseOrValue<BigNumberish>,
      srcAddress: PromiseOrValue<string>,
      dstAddress: PromiseOrValue<string>,
      sequence: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    validateTransactionProof(
      srcChainId: PromiseOrValue<BigNumberish>,
      srcBlockHash: PromiseOrValue<BytesLike>,
      logIndex: PromiseOrValue<BigNumberish>,
      mptProof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    zkBridgeContracts(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  MESSAGE_TOPIC(overrides?: CallOverrides): Promise<string>;

  MIN_LOCK_TIME(overrides?: CallOverrides): Promise<BigNumber>;

  blockUpdater(
    chainId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  chainId(overrides?: CallOverrides): Promise<number>;

  claimFees(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  confirmContractUpgrade(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isInitialized(
    impl: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isL2(overrides?: CallOverrides): Promise<boolean>;

  isTransferCompleted(
    hash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  l2MessageReceive(
    chainId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  l2MessageSend(overrides?: CallOverrides): Promise<string>;

  lockTime(overrides?: CallOverrides): Promise<BigNumber>;

  mptVerifier(
    chainId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  nextSequence(
    hash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  pendingImplementation(overrides?: CallOverrides): Promise<string>;

  registerChain(
    chainId: PromiseOrValue<BigNumberish>,
    bridgeContract: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  send(
    dstChainId: PromiseOrValue<BigNumberish>,
    dstAddress: PromiseOrValue<string>,
    payload: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendFromL2(
    srcChainId: PromiseOrValue<BigNumberish>,
    dstChainId: PromiseOrValue<BigNumberish>,
    dstAddress: PromiseOrValue<string>,
    payload: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBlockUpdater(
    chainId: PromiseOrValue<BigNumberish>,
    blockUpdater: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setL2(
    isL2: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setL2MessageReceive(
    chainId: PromiseOrValue<BigNumberish>,
    l2MessageReceive: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setL2MessageSend(
    l2MessageSend: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLockTime(
    lockTime: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMptVerifier(
    chainId: PromiseOrValue<BigNumberish>,
    mptVerifier: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitContractUpgrade(
    newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  toUpdateTime(overrides?: CallOverrides): Promise<BigNumber>;

  validateTransactionFromL2(
    srcChainId: PromiseOrValue<BigNumberish>,
    srcAddress: PromiseOrValue<string>,
    dstAddress: PromiseOrValue<string>,
    sequence: PromiseOrValue<BigNumberish>,
    payload: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  validateTransactionProof(
    srcChainId: PromiseOrValue<BigNumberish>,
    srcBlockHash: PromiseOrValue<BytesLike>,
    logIndex: PromiseOrValue<BigNumberish>,
    mptProof: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  zkBridgeContracts(
    chainId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    MESSAGE_TOPIC(overrides?: CallOverrides): Promise<string>;

    MIN_LOCK_TIME(overrides?: CallOverrides): Promise<BigNumber>;

    blockUpdater(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    chainId(overrides?: CallOverrides): Promise<number>;

    claimFees(overrides?: CallOverrides): Promise<void>;

    confirmContractUpgrade(overrides?: CallOverrides): Promise<void>;

    initialize(overrides?: CallOverrides): Promise<void>;

    isInitialized(
      impl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isL2(overrides?: CallOverrides): Promise<boolean>;

    isTransferCompleted(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    l2MessageReceive(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    l2MessageSend(overrides?: CallOverrides): Promise<string>;

    lockTime(overrides?: CallOverrides): Promise<BigNumber>;

    mptVerifier(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    nextSequence(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    pendingImplementation(overrides?: CallOverrides): Promise<string>;

    registerChain(
      chainId: PromiseOrValue<BigNumberish>,
      bridgeContract: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    send(
      dstChainId: PromiseOrValue<BigNumberish>,
      dstAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sendFromL2(
      srcChainId: PromiseOrValue<BigNumberish>,
      dstChainId: PromiseOrValue<BigNumberish>,
      dstAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBlockUpdater(
      chainId: PromiseOrValue<BigNumberish>,
      blockUpdater: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setL2(
      isL2: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setL2MessageReceive(
      chainId: PromiseOrValue<BigNumberish>,
      l2MessageReceive: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setL2MessageSend(
      l2MessageSend: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLockTime(
      lockTime: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMptVerifier(
      chainId: PromiseOrValue<BigNumberish>,
      mptVerifier: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    submitContractUpgrade(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    toUpdateTime(overrides?: CallOverrides): Promise<BigNumber>;

    validateTransactionFromL2(
      srcChainId: PromiseOrValue<BigNumberish>,
      srcAddress: PromiseOrValue<string>,
      dstAddress: PromiseOrValue<string>,
      sequence: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    validateTransactionProof(
      srcChainId: PromiseOrValue<BigNumberish>,
      srcBlockHash: PromiseOrValue<BytesLike>,
      logIndex: PromiseOrValue<BigNumberish>,
      mptProof: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    zkBridgeContracts(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "ContractUpgraded(address,address)"(
      oldContract?: PromiseOrValue<string> | null,
      newContract?: PromiseOrValue<string> | null
    ): ContractUpgradedEventFilter;
    ContractUpgraded(
      oldContract?: PromiseOrValue<string> | null,
      newContract?: PromiseOrValue<string> | null
    ): ContractUpgradedEventFilter;

    "ExecutedMessage(address,uint16,uint64,address,bytes)"(
      sender?: PromiseOrValue<string> | null,
      srcChainId?: PromiseOrValue<BigNumberish> | null,
      sequence?: PromiseOrValue<BigNumberish> | null,
      dstAddress?: null,
      payload?: null
    ): ExecutedMessageEventFilter;
    ExecutedMessage(
      sender?: PromiseOrValue<string> | null,
      srcChainId?: PromiseOrValue<BigNumberish> | null,
      sequence?: PromiseOrValue<BigNumberish> | null,
      dstAddress?: null,
      payload?: null
    ): ExecutedMessageEventFilter;

    "MessagePublished(address,uint16,uint64,address,bytes)"(
      sender?: PromiseOrValue<string> | null,
      dstChainId?: PromiseOrValue<BigNumberish> | null,
      sequence?: PromiseOrValue<BigNumberish> | null,
      dstAddress?: null,
      payload?: null
    ): MessagePublishedEventFilter;
    MessagePublished(
      sender?: PromiseOrValue<string> | null,
      dstChainId?: PromiseOrValue<BigNumberish> | null,
      sequence?: PromiseOrValue<BigNumberish> | null,
      dstAddress?: null,
      payload?: null
    ): MessagePublishedEventFilter;

    "NewPendingImplementation(address,address)"(
      pendingImplementation?: PromiseOrValue<string> | null,
      newImplementation?: PromiseOrValue<string> | null
    ): NewPendingImplementationEventFilter;
    NewPendingImplementation(
      pendingImplementation?: PromiseOrValue<string> | null,
      newImplementation?: PromiseOrValue<string> | null
    ): NewPendingImplementationEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
  };

  estimateGas: {
    MESSAGE_TOPIC(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_LOCK_TIME(overrides?: CallOverrides): Promise<BigNumber>;

    blockUpdater(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    chainId(overrides?: CallOverrides): Promise<BigNumber>;

    claimFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    confirmContractUpgrade(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isInitialized(
      impl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isL2(overrides?: CallOverrides): Promise<BigNumber>;

    isTransferCompleted(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    l2MessageReceive(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    l2MessageSend(overrides?: CallOverrides): Promise<BigNumber>;

    lockTime(overrides?: CallOverrides): Promise<BigNumber>;

    mptVerifier(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextSequence(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pendingImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    registerChain(
      chainId: PromiseOrValue<BigNumberish>,
      bridgeContract: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    send(
      dstChainId: PromiseOrValue<BigNumberish>,
      dstAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendFromL2(
      srcChainId: PromiseOrValue<BigNumberish>,
      dstChainId: PromiseOrValue<BigNumberish>,
      dstAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBlockUpdater(
      chainId: PromiseOrValue<BigNumberish>,
      blockUpdater: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setL2(
      isL2: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setL2MessageReceive(
      chainId: PromiseOrValue<BigNumberish>,
      l2MessageReceive: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setL2MessageSend(
      l2MessageSend: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLockTime(
      lockTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMptVerifier(
      chainId: PromiseOrValue<BigNumberish>,
      mptVerifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitContractUpgrade(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    toUpdateTime(overrides?: CallOverrides): Promise<BigNumber>;

    validateTransactionFromL2(
      srcChainId: PromiseOrValue<BigNumberish>,
      srcAddress: PromiseOrValue<string>,
      dstAddress: PromiseOrValue<string>,
      sequence: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    validateTransactionProof(
      srcChainId: PromiseOrValue<BigNumberish>,
      srcBlockHash: PromiseOrValue<BytesLike>,
      logIndex: PromiseOrValue<BigNumberish>,
      mptProof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    zkBridgeContracts(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MESSAGE_TOPIC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_LOCK_TIME(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    blockUpdater(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    chainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    confirmContractUpgrade(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isInitialized(
      impl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isL2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isTransferCompleted(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l2MessageReceive(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l2MessageSend(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lockTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mptVerifier(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextSequence(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerChain(
      chainId: PromiseOrValue<BigNumberish>,
      bridgeContract: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    send(
      dstChainId: PromiseOrValue<BigNumberish>,
      dstAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendFromL2(
      srcChainId: PromiseOrValue<BigNumberish>,
      dstChainId: PromiseOrValue<BigNumberish>,
      dstAddress: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBlockUpdater(
      chainId: PromiseOrValue<BigNumberish>,
      blockUpdater: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setL2(
      isL2: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setL2MessageReceive(
      chainId: PromiseOrValue<BigNumberish>,
      l2MessageReceive: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setL2MessageSend(
      l2MessageSend: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLockTime(
      lockTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMptVerifier(
      chainId: PromiseOrValue<BigNumberish>,
      mptVerifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitContractUpgrade(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    toUpdateTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    validateTransactionFromL2(
      srcChainId: PromiseOrValue<BigNumberish>,
      srcAddress: PromiseOrValue<string>,
      dstAddress: PromiseOrValue<string>,
      sequence: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    validateTransactionProof(
      srcChainId: PromiseOrValue<BigNumberish>,
      srcBlockHash: PromiseOrValue<BytesLike>,
      logIndex: PromiseOrValue<BigNumberish>,
      mptProof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    zkBridgeContracts(
      chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
