/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBlockUpdater } from "./IBlockUpdater";
export type { ICrossDomainMessenger } from "./ICrossDomainMessenger";
export type { IL2MessageSend } from "./IL2MessageSend";
export type { IMessageService } from "./IMessageService";
export type { IMptVerifier } from "./IMptVerifier";
export type { IZKBridgeEntrypoint } from "./IZKBridgeEntrypoint";
export type { IZKBridgeReceiver } from "./IZKBridgeReceiver";
