/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IL2MessageSend,
  IL2MessageSendInterface,
} from "../../../contracts/interfaces/IL2MessageSend";

const _abi = [
  {
    inputs: [],
    name: "getFee",
    outputs: [
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_srcChainId",
        type: "uint16",
      },
      {
        internalType: "address",
        name: "_srcAddress",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "_dstChainId",
        type: "uint16",
      },
      {
        internalType: "address",
        name: "_dstAddress",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "_sequence",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "_payload",
        type: "bytes",
      },
    ],
    name: "sendMessage",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IL2MessageSend__factory {
  static readonly abi = _abi;
  static createInterface(): IL2MessageSendInterface {
    return new utils.Interface(_abi) as IL2MessageSendInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL2MessageSend {
    return new Contract(address, _abi, signerOrProvider) as IL2MessageSend;
  }
}
